inherit_from: .rubocop_todo.yml

inherit_gem:
  mapotempo_rubocop:
    - rubocop-default.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'tmp/**/*'
    - 'vendor/bundle/**/*'
    - 'config/initializers/local.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

# Disabled since it defers/pushes final verifications after a return which hides the verification logic.
#
# It is disabled by other tech companies with similar reasons:
# https://github.com/airbnb/ruby/blob/12435e8136d2adf710de999bc0f6bef01215df2c/rubocop-airbnb/config/rubocop-style.yml#L363
# https://github.com/Shopify/ruby-style-guide/blob/f604033657c54fa0dc28b5914c1e6c2641e6f361/rubocop.yml#L469
Style/GuardClause:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

# Style/UnlessLogicalOperators: # TODO: activate when rubocop gem is upgraded
#   EnforcedStyle: forbid_logical_operators

Layout/EmptyLines:
  Severity: warning

Layout/ExtraSpacing:
  Severity: warning

Layout/IndentationConsistency:
  Severity: warning

Layout/IndentationWidth:
  Severity: warning

# Layout/LineLength:
#   Enabled: false