language: ruby
rvm:
  - 2.3.3

env: # Tests are ordered so that they finish faster when run on three parallel threads by Travis
  - TEST_SUITE='basis'
  - TEST_SUITE='dicho'
  - TEST_SUITE='scheduling'
  - TEST_SUITE='real_scheduling'
  - TEST_SUITE='real_scheduling_solver'
  - TEST_SUITE='split_clustering'
  - TEST_SUITE='real'
  # - TEST_SUITE='real_dicho' -> should be runned locally because test are too big to dump matrices

services:
  - docker

cache: bundler

before_install:
  - gem install bundler --version 1.17.3
  - export REGISTRY=registry.mapotempo.com/
  - docker build -t ${REGISTRY}mapotempo-ce/optimizer-api:latest -f docker/Dockerfile --build-arg ORTOOLS_VERSION=v7.0 --build-arg VROOM_VERSION=v1.2.0 --build-arg OPTIMIZER_ORTOOLS_VERSION=${OPTIMIZER_ORTOOLS_VERSION:-latest} .
  - docker swarm init
  - mkdir -p ./redis

install:

script:
  - travis_wait 50 bash ci-utils/travis.sh ${TEST_SUITE}
