language: ruby

env:
  - TEST_SUITE='basis'
  - TEST_SUITE='real'
  - TEST_SUITE='scheduling'

services:
  - docker

cache: bundle

before_install:
  - gem update --system
  - gem install bundler
  - export REGISTRY=registry.mapotempo.com/
  - docker build -t ${REGISTRY}mapotempo-ce/optimizer-api:latest -f docker/Dockerfile --build-arg ORTOOLS_VERSION=v6.5 --build-arg VROOM_VERSION=v1.2.0 --build-arg OPTIMIZER_ORTOOLS_VERSION=v6.5 .
  - docker swarm init
  - mkdir -p ./redis

script:
  - bash ci-utils/travis.sh ${TEST_SUITE}
