language: ruby

services:
  - docker

cache: bundle

before_install:
  - docker build -t mapotempo/optimizer-api:latest -f docker/Dockerfile --build-arg ORTOOLS_VERSION=v6.5 --build-arg VROOM_VERSION=v1.2.0 .
  - docker swarm init
  - mkdir -p ./test/redis
  - docker stack deploy -c ./test/docker-compose.yml optimizer

script:
  - DOCKER_SERVICE_NAME=optimizer_api
  - CONTAINER=${DOCKER_SERVICE_NAME}.1.$(docker service ps -f "name=${DOCKER_SERVICE_NAME}.1" ${DOCKER_SERVICE_NAME} -q --no-trunc | head -n1)
  - docker exec -i ${CONTAINER} apt update -y > /dev/null
  - docker exec -i ${CONTAINER} apt install git -y > /dev/null
  - docker exec -i ${CONTAINER} rm /srv/app/.bundle/config
  - docker exec -i ${CONTAINER} bundle install
  - docker exec -i ${CONTAINER} bundle exec rake test
