version: '3.7'

x-default-service: &default-service
  build: .
  image: optimizer-api:${CARTOROUTE_VERSION:-latest}
  environment: &default-environment
    LOG_LEVEL: ${LOG_LEVEL:-info}
    OPTIM_DEFAULT_MAX_LATENESS_RATIO: 1
    OPTIM_GENERATE_GEOJSON_POLYLINES: 'true'
    REDIS_COUNT_HOST: redis-count
    # REDIS_CACHE_HOST: redis-cache
    REDIS_RESQUE_HOST: redis-resque
    REDIS_RESULT_TTL_DAYS: ${REDIS_RESULT_TTL_DAYS:-1}
    ROUTER_URL: ${ROUTER_URL:-http://localhost:4899/0.1}
    ROUTER_API_KEY: ${ROUTER_API_KEY:-demo}
    SENTRY_DSN: ${SENTRY_DSN:-}
  links:
    - redis-resque
    # - redis-cache
    - redis-count
  volumes:
    - .:/srv/app
    - ./docker/production.rb:/srv/app/config/environments/production.rb
    - ./docker/production.rb:/srv/app/config/environments/development.rb

services:
  redis-resque:
    image: redis:${REDIS_VERSION:-7-alpine}
    command: redis-server --appendonly yes

  # redis-cache:
  #   image: redis:${REDIS_VERSION:-7-alpine}
  #   command: redis-server --save ""

  redis-count:
    image: redis:${REDIS_VERSION:-7-alpine}
    volumes:
      - ./docker/redis-count:/data
    command: redis-server --appendonly yes

  api:
    <<: *default-service
    ports:
      - "8083:80" # HOST:CONTAINER, edit only HOST part
    command: bundle exec puma -v -p 80 --pidfile 'server.pid'

  resque-default:
    <<: *default-service
    environment:
      <<: *default-environment
      COUNT: 5
      QUEUES: DEFAULT
    command: bundle exec rake resque:workers --trace
