version: '3.7'

x-default-redis: &default-redis
  image: redis:7-alpine
  command: redis-server --appendonly yes
  networks:
    - optimizer-network
  deploy:
    restart_policy:
      condition: any

x-default-service: &default-service
  image: optimizer-api:latest
  environment: &default-environment
    APP_ENV: test
    BUNDLE_WITH: "test development"
    LOG_LEVEL: fatal
    OPTIM_DEFAULT_MAX_LATENESS_RATIO: 1
    OPTIM_GENERATE_GEOJSON_POLYLINES: 'true'
    REDIS_COUNT_HOST: redis-count
    REDIS_RESQUE_HOST: redis-resque
    REDIS_RESULT_TTL_DAYS: 1
    DOCKER: 'true'
  networks:
    - optimizer-network
  depends_on:
    - redis-resque

services:
  api:
    <<: *default-service
    ports:
      - "8083:80"
    command: bundle exec puma -v -p 80 --pidfile 'server.pid'
    networks:
      - optimizer-network

  resque-default:
    <<: *default-service
    environment:
      <<: *default-environment
      COUNT: 5
      QUEUES: DEFAULT
    command: bundle exec rake resque:workers --trace
    networks:
      - optimizer-network

  redis-resque:
    <<: *default-redis
    networks:
      - optimizer-network
  redis-count:
    <<: *default-redis
    volumes:
      - ${APP_HOME:-..}/redis-count:/data
    hostname: redis-count


networks:
  optimizer-network:
    driver: overlay
