version: '2'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/optimizer-api:${MAPOTEMPO_VERSION:-latest}
    ports:
      - "8083:80" # HOST:CONTAINER, edit only HOST part
    volumes:
      - ./production.rb:/srv/app/config/environments/production.rb
      - ./production.rb:/srv/app/config/environments/development.rb
    links:
      - redis-cache
    environment:
      APP_ENV: production # Swith to "development" for more traces

  resque-default:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/optimizer-api:${MAPOTEMPO_VERSION:-latest}
    volumes:
      - ./production.rb:/srv/app/config/environments/production.rb
    links:
        - redis-cache
    command: /bin/bash -c "cd /srv/app && APP_ENV=production COUNT=5 QUEUE=DEFAULT /usr/bin/bundle exec rake resque:workers"

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""
