version: '3.7'
services:
  redis:
    image: redis:${REDIS_VERSION:-6.2.5-alpine}
    hostname: redis
    volumes:
      - ${APP_HOME:-..}/redis:/data
    command: redis-server --appendonly yes
    networks:
      - resque

  redis-cache:
    image: redis:${REDIS_VERSION:-6.2.5-alpine}
    hostname: redis-cache
    volumes:
      - ${APP_HOME:-..}/redis:/data
    command: redis-server --save ""
    networks:
      - redis_cache

  redis-count:
    image: redis:${REDIS_VERSION:-6.2.5-alpine}
    volumes:
      - ${APP_HOME:-..}/redis-count:/data
    hostname: redis-count
    command: redis-server --appendonly yes
    deploy:
      restart_policy:
        condition: any
    networks:
      - redis_count

  api:
    image: registry.test.com/mapotempo/optimizer-api:latest
    environment:
      PASSENGER_APP_ENV: test
      REDIS_COUNT_HOST: redis-count
      REDIS_HOST: redis-cache
      REDIS_RESQUE_HOST: redis
    networks:
      - base
      - redis_cache
      - redis_count
      - resque

  resque-default:
    image: registry.test.com/mapotempo/optimizer-api:latest
    working_dir: /srv/app
    environment:
      APP_ENV: test
      COUNT: 5
      QUEUES: DEFAULT
      REDIS_COUNT_HOST: redis-count
      REDIS_HOST: redis-cache
      REDIS_RESQUE_HOST: redis
      ROUTER_API_KEY: ${ROUTER_API_KEY:-demo}
      ROUTER_URL: ${ROUTER_URL:-http://localhost:4899/0.1}
    command: bundle exec rake resque:workers
    networks:
      - redis_cache
      - redis_count
      - resque

networks:
  base:
  redis_cache:
  redis_count:
  resque:
